
import { Language, Product } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ku: {
    shop_name: 'DEVAN BRAND',
    cart: 'سەبەتە',
    checkout: 'تەواوکردنی کڕین',
    invoice: 'فاکتۆر',
    pos: 'سیستەمی فرۆشتن',
    home: 'سەرەتا',
    products: 'کاڵاکان',
    add_to_cart: 'بخە ناو سەبەتە',
    total: 'کۆی گشتی',
    price: 'نرخ',
    quantity: 'بڕ',
    payment_method: 'شێوازی پارەدان',
    print_invoice: 'چاپکردنی فاکتۆر',
    download_pdf: 'داگرتنی PDF',
    send_whatsapp: 'ناردنی پارە و پسوڵە (WhatsApp)',
    whatsapp_instruction: 'بۆ ناردنی پارە، دەتوانیت زانیارییەکان بنێریت بۆ ئەم واتس ئاپە:',
    cash: 'نەختینە',
    fib: 'FIB',
    fastpay: 'FastPay',
    qicard: 'Qi Card',
    search: 'بگەڕێ...',
    order_success: 'داواکارییەکە بە سەرکەوتوویی تۆمارکرا',
    empty_cart: 'سەبەتەکەت بەتاڵە',
    suggest_ai: 'پێشنیاری زیرەکی دەستکرد',
    customer_name: 'ناوی سیانی کڕیار',
    customer_address: 'ناونیشانی کڕیار',
    customer_phone: 'ژمارە تەلەفۆن',
    discount: 'داشکان (دینار)',
    final_total: 'کۆی کۆتایی',
    date: 'بەروار',
    items: 'کاڵاکان',
    admin_panel: 'بەڕێوەبردن',
    revenue: 'کۆی داهات',
    stock: 'کۆگا',
    edit: 'دەستکاری',
    delete: 'سڕینەوە',
    add_product: 'زیادکردنی کاڵا',
    save: 'پاشەکەوتکردن',
    out_of_stock: 'نەماوە',
    low_stock: 'کەم ماوە',
    product_image: 'وێنەی کاڵا (بارکردن)',
    product_description: 'ناساندنی جۆری کاڵا',
    category: 'پۆلێن',
    visitors_daily: 'سەردانیکەری ئەمڕۆ',
    visitors_total: 'کۆی سەردانیکەران'
  },
  ar: {
    shop_name: 'DEVAN BRAND',
    cart: 'عربة التسوق',
    checkout: 'الدفع',
    invoice: 'فاتورة',
    pos: 'نظام البيع',
    home: 'الرئيسية',
    products: 'المنتجات',
    add_to_cart: 'إضافة إلى السلة',
    total: 'المجموع',
    price: 'السعر',
    quantity: 'الكمية',
    payment_method: 'طريقة الدفع',
    print_invoice: 'طباعة الفاتورة',
    download_pdf: 'تحميل PDF',
    send_whatsapp: 'إرسال الدفع والفاتورة (WhatsApp)',
    whatsapp_instruction: 'لإرسال الأموال، يمكنك إرسال المعلومات إلى هذا الواتساب:',
    cash: 'نقدًا',
    fib: 'FIB',
    fastpay: 'FastPay',
    qicard: 'Qi Card',
    search: 'بحث...',
    order_success: 'تم تسجيل الطلب بنجاح',
    empty_cart: 'عربة التسوق فارغة',
    suggest_ai: 'اقتراح الذكاء الاصطناعي',
    customer_name: 'الاسم الثلاثي للعميل',
    customer_address: 'عنوان العميل',
    customer_phone: 'رقم الهاتف',
    discount: 'خصم (دینار)',
    final_total: 'المجموع النهائي',
    date: 'التاريخ',
    items: 'العناصر',
    admin_panel: 'لوحة التحكم',
    revenue: 'إجمالي الإيرادات',
    stock: 'المخزن',
    edit: 'تعديل',
    delete: 'حذف',
    add_product: 'إضافة منتج',
    save: 'حفظ',
    out_of_stock: 'نفذت الكمية',
    low_stock: 'كمية منخفضة',
    product_image: 'صورة المنتج (تحميل)',
    product_description: 'وصف نوع المنتج',
    category: 'الفئة',
    visitors_daily: 'زوار اليوم',
    visitors_total: 'إجمالي الزوار'
  },
  en: {
    shop_name: 'DEVAN BRAND',
    cart: 'Cart',
    checkout: 'Checkout',
    invoice: 'Invoice',
    pos: 'POS System',
    home: 'Home',
    products: 'Products',
    add_to_cart: 'Add to Cart',
    total: 'Total',
    price: 'Price',
    quantity: 'Qty',
    payment_method: 'Payment Method',
    print_invoice: 'Print Invoice',
    download_pdf: 'Download PDF',
    send_whatsapp: 'Send Payment & Invoice (WhatsApp)',
    whatsapp_instruction: 'To send money, you can send the info to this WhatsApp:',
    cash: 'Cash',
    fib: 'FIB',
    fastpay: 'FastPay',
    qicard: 'Qi Card',
    search: 'Search...',
    order_success: 'Order placed successfully',
    empty_cart: 'Your cart is empty',
    suggest_ai: 'AI Suggestion',
    customer_name: 'Customer Full Name',
    customer_address: 'Customer Address',
    customer_phone: 'Phone Number',
    discount: 'Discount (IQD)',
    final_total: 'Final Total',
    date: 'Date',
    items: 'Items',
    admin_panel: 'Admin Panel',
    revenue: 'Total Revenue',
    stock: 'Stock',
    edit: 'Edit',
    delete: 'Delete',
    add_product: 'Add Product',
    save: 'Save',
    out_of_stock: 'Out of Stock',
    low_stock: 'Low Stock',
    product_image: 'Product Image (Upload)',
    product_description: 'Product Description/Type',
    category: 'Category',
    visitors_daily: 'Daily Visitors',
    visitors_total: 'Total Visitors'
  }
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: { ku: 'تیشێرتی ڕەش - لیمیتد', ar: 'تيشيرت أسود - إصدار محدود', en: 'Black T-Shirt - Limited Edition' },
    description: { ku: 'قوماشی نایاب و نەرم بۆ وەرزی هاوین', ar: 'قماش ممتاز وناعم لفصل الصيف', en: 'Premium soft fabric for summer season' },
    price: 25000,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=400&h=400&fit=crop',
    stock: 15
  },
  {
    id: 2,
    name: { ku: 'پانتۆڵی جینز - شینی تۆخ', ar: 'بنطلون جينز - أزرق داكن', en: 'Denim Jeans - Dark Blue' },
    description: { ku: 'ستایلی مۆدێرن و گونجاو بۆ هەموو تەمەنێک', ar: 'ستايل عصري ومناسب لجميع الأعمار', en: 'Modern style suitable for all ages' },
    price: 45000,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=400&h=400&fit=crop',
    stock: 8
  },
  {
    id: 3,
    name: { ku: 'سەعاتی دیڤان - زیوین', ar: 'ساعة ديفان - فضية', en: 'Devan Watch - Silver' },
    description: { ku: 'دیزاینێکی ناوازە و گونجاو بۆ بۆنە فەرمییەکان', ar: 'تصميم رائع ومناسب للمناسبات الرسمية', en: 'Exquisite design suitable for formal occasions' },
    price: 125000,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=400&h=400&fit=crop',
    stock: 3
  }
];
